bindPort = 7000

vhostHTTPPort = 8080

auth.method = "token"
auth.token = "12345678"

log.to = "./frps.log"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "opennhp-frp"
webServer.password = "opennhp-frp"

subDomainHost = "opennhp.online"
